const RECIEVED_EMPTY_FIELD = "RECIEVED_EMPTY_FIELD"
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
const WRONG_CREDENTIALS = "WRONG_CREDENTIALS"
const INVALID_JSON_BODY = "INVALID_JSON_BODY"
const INVALID_URL = "INVALID_URL"
const NO_USER_FOUND = "NO_USER_FOUND"
const INVALID_TOKEN = "INVALID_TOKEN"
const NOT_ADMIN = "NOT_ADMIN"
const INVALID_DATA_FORMAT = "INVALID_DATA_FORMAT"
const INVALID_EMAIL = "INVALID_EMAIL"
const WEAK_PASSWORD = "WEAK_PASSWORD"
const PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH"
const TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS"

module.exports = {
  RECIEVED_EMPTY_FIELD,
  EMAIL_ALREADY_EXISTS,
  WRONG_CREDENTIALS,
  INVALID_JSON_BODY,
  INVALID_URL,
  NO_USER_FOUND,
  INVALID_TOKEN,
  NOT_ADMIN,
  INVALID_DATA_FORMAT,
  INVALID_EMAIL,
  WEAK_PASSWORD,
  PASSWORD_NOT_MATCH,
  TOO_MANY_ATTEMPTS
}